### ISSUE TITLE
cluster coverages on by default

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk#103]
## How to reproduce

- SMK version I'm using: 1.0.2
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: Win 10

## What behaviour I'm expecting and which behaviour I'm seeing
When you cluster points data the cluster hulls are on by default.  It is preferable that they should be turned off by default.  This has been controlled in a previous pre-MVP version of SMK by the viewer property **showCoverageOnHover**

Will create a complimentary ticket for smk-cli enhancement.

**Comment by NicoledeGreef** [comment]
was previously implemented as:
![image](https://user-images.githubusercontent.com/26335003/123492449-63d7d300-d5ce-11eb-9bb0-aac6d344366b.png)

**Comment by michaelpnelson** [comment]
In version 1.0.5, clusterOption.showCoverageOnHover is false by default. I reviewed our code and we set a default value of false in smk.js (https://github.com/bcgov/smk/blame/375e57ec506dbf097a587c443725d032797b54b0/src/smk.js#L729).

**Comment by michaelpnelson** [comment]
In further testing, I do see that a vector layer's clustering shows coverage on hover when no clusterOption.showCoverageOnHover value is set in smk-config.json. I'll reopen this while I investigate further.

**Comment by michaelpnelson** [comment]
I have a better understanding of this now. My observation of coverage on hover in my last comment was affected by local changes I was making (for https://github.com/bcgov/smk-cli/issues/63) that I didn't think would be related but were a cause.

We set viewer.clusterOption.showCoverageOnHover to false by default in smk.js when we are setting up the structure of the configuration in setupGlobalSMK(). In layer-vector-leaflet.js, in the clusterOptions() function, we then create and populate cluster options. Then when we consume these options in marker-cluster-1.0.6.js, if we haven't specifically set a value, a default of 'true' is used. 

layer-vector-leaflet.js was amended to set a value in the options based on the value of showCoverageOnHover, either from the 'viewer' section of smk-config.json, or using the default 'false' set in smk.js. This was fixed in https://github.com/bcgov/smk/issues/104, and I've confirmed in local testing that showCoverageOnHover is false unless specifically set to true in smk-config.json in the 'viewer' section.
