### ISSUE TITLE
integrate with the Geomark web service

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk#97]
DataBC hosts a Geomark web service that can be used to share immutable geometries between systems.  This is valuable in maps that support permit applications.

Existing Geomark task in DMF:
![image](https://user-images.githubusercontent.com/26335003/105417363-5d44ca00-5bf0-11eb-8839-50c47c86ebff.png)

See also iMapBC's integration:
![image](https://user-images.githubusercontent.com/26335003/105418072-62564900-5bf1-11eb-95ca-dd9beec81a80.png)

The iMapBC implementation has better UI design than the DMF.

![image](https://user-images.githubusercontent.com/26335003/105419864-3ab4b000-5bf4-11eb-94c9-6f5e29c3ba2e.png)
![image](https://user-images.githubusercontent.com/26335003/105419888-47390880-5bf4-11eb-9c67-48b24c519551.png)

**Comment by qqnluaq** [comment]
I presume this integration would take the form of tools for loading geomarks and saving geomarks.
These could be the same tool.
An example of how this could be implemented is shown at https://portal.nrs.gov.bc.ca/cwmc-lib/v1.9.0/sdk/examples/showcase/: 
![image](https://user-images.githubusercontent.com/20274603/106021697-e8ebaa00-6079-11eb-95a1-1759873eaeb3.png)
The import and export tools in CWM support more formats besides Geomark. 

Loading a geomark:
1. get URL from user
2. get a layer title from user
3. let user select the style for displaying the geometry (stroke color, fill color, marker shape, ...?)
4. load geometry and place on map using the selected style
5. add geomark layer to layer list in a folder. The name of the folder, and its placement in the layer list determined by configuration.

Saving a geomark:
1. Identify the target geometry to save. There are 2 possible sources: the selection tool or the markup tool.
2. submit geometry to geomark service
3. present user with the geomark URL that the service returns.

I'll estimate 5 days for this work

**Comment by qqnluaq** [comment]
For this tool to be useful, the geometry sources must be functional. 
The selection tool can grab the geometry from a feature on the map, but offers no way to edit or otherwise manipulate that geometry.
The markup tool allows you draw on that map, and thats it. The geometry drawn is not organized in any way. There is no styling possible. You can edit the geometries however.

I propose some improvements to markup & selection:
1. a way organize markup geometries. A folder in the layer list that contains all markup objects is probably the simplest.
2. a way to copy the geometry of a feature in the selection to markup

estimate 3 days for this work

**Comment by michaelpnelson** [comment]
Geomark functionality was integrated in pull request https://github.com/bcgov/smk/pull/147, after which SMK 1.0.7 was released. Closing this issue.
